package com.nomanr.lumo.plugin.template.template_registry

enum class SupportedComponents {
    Accordion,
    AlertDialog,
    Badge,
    Button,
    Card,
    Checkbox,
    Chip,
    Divider,
    Icon,
    IconButton,
    ModalBottomSheet,
    NavigationBar,
    OTPTextField,
    ProgressIndicators,
    RadioButton,
    Scaffold,
    Slider,
    Surface,
    Snackbar,
    Switch,
    SystemBars,
    Text,
    TextField,
    Theme,
    Tooltip,
    TopBar,
}